materials:
  basic:
    label: normal steel
    mass: 50
    armor: 10
    hp: 100
    recoverPerSecond: 10
    color: "#66788d"
  reinforced:
    label: Reinforced
    mass: 13
    armor: 1.3
    hp: 150
    recoverPerSecond: 1.9
    color: "#8ca3bd"
  ceramic:
    label: heavy steel
    mass: 100
    armor: 15
    hp: 200
    recoverPerSecond: 20
    color: "#3f4b5a"
  reactive:
    label: Reactive
    mass: 14
    armor: 1.55
    hp: 170
    recoverPerSecond: 1.7
    color: "#d0bb90"
  combined:
    label: Combined Mk1
    mass: 12
    armor: 1.5
    hp: 165
    recoverPerSecond: 1.8
    color: "#bda9d8"
