# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import arena_service_pb2 as arena__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arena_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArenaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBattle = channel.unary_unary(
                '/arena.v1.ArenaService/CreateBattle',
                request_serializer=arena__service__pb2.CreateBattleRequest.SerializeToString,
                response_deserializer=arena__service__pb2.BattleStepResponse.FromString,
                _registered_method=True)
        self.StepBattle = channel.unary_unary(
                '/arena.v1.ArenaService/StepBattle',
                request_serializer=arena__service__pb2.StepBattleRequest.SerializeToString,
                response_deserializer=arena__service__pb2.BattleStepResponse.FromString,
                _registered_method=True)
        self.GetBattle = channel.unary_unary(
                '/arena.v1.ArenaService/GetBattle',
                request_serializer=arena__service__pb2.GetBattleRequest.SerializeToString,
                response_deserializer=arena__service__pb2.BattleStepResponse.FromString,
                _registered_method=True)
        self.CloseBattle = channel.unary_unary(
                '/arena.v1.ArenaService/CloseBattle',
                request_serializer=arena__service__pb2.CloseBattleRequest.SerializeToString,
                response_deserializer=arena__service__pb2.CloseBattleResponse.FromString,
                _registered_method=True)


class ArenaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBattle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepBattle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBattle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseBattle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArenaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBattle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBattle,
                    request_deserializer=arena__service__pb2.CreateBattleRequest.FromString,
                    response_serializer=arena__service__pb2.BattleStepResponse.SerializeToString,
            ),
            'StepBattle': grpc.unary_unary_rpc_method_handler(
                    servicer.StepBattle,
                    request_deserializer=arena__service__pb2.StepBattleRequest.FromString,
                    response_serializer=arena__service__pb2.BattleStepResponse.SerializeToString,
            ),
            'GetBattle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBattle,
                    request_deserializer=arena__service__pb2.GetBattleRequest.FromString,
                    response_serializer=arena__service__pb2.BattleStepResponse.SerializeToString,
            ),
            'CloseBattle': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseBattle,
                    request_deserializer=arena__service__pb2.CloseBattleRequest.FromString,
                    response_serializer=arena__service__pb2.CloseBattleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arena.v1.ArenaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arena.v1.ArenaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArenaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBattle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/CreateBattle',
            arena__service__pb2.CreateBattleRequest.SerializeToString,
            arena__service__pb2.BattleStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepBattle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/StepBattle',
            arena__service__pb2.StepBattleRequest.SerializeToString,
            arena__service__pb2.BattleStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBattle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/GetBattle',
            arena__service__pb2.GetBattleRequest.SerializeToString,
            arena__service__pb2.BattleStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseBattle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arena.v1.ArenaService/CloseBattle',
            arena__service__pb2.CloseBattleRequest.SerializeToString,
            arena__service__pb2.CloseBattleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
