import type { ComponentId, ComponentStats } from "../../types.ts";
import { PROJECTILE_GRAVITY } from "./range.ts";

export const COMPONENTS: Record<ComponentId, ComponentStats> = {
  control: { mass: 8, hpMul: 0.9, type: "control" },
  engineS: {
    mass: 10,
    hpMul: 1.0,
    type: "engine",
    power: 92,
    maxSpeed: 96,
    propulsion: { platform: "ground", mode: "omni" },
  },
  engineM: {
    mass: 16,
    hpMul: 1.0,
    type: "engine",
    power: 142,
    maxSpeed: 122,
    propulsion: { platform: "ground", mode: "omni" },
  },
  jetEngine: {
    mass: 14,
    hpMul: 0.8,
    type: "engine",
    power: 154,
    maxSpeed: 150,
    propulsion: { platform: "air", mode: "omni", preferVertical: true },
  },
  propeller: {
    mass: 9,
    hpMul: 0.45,
    type: "engine",
    power: 260,
    maxSpeed: 180,
    directional: true,
    propulsion: {
      platform: "air",
      mode: "directional",
      thrustAngleDeg: 95,
      preferVertical: true,
    },
    placement: {
      footprintOffsets: [{ x: 0, y: 0 }, { x: 1, y: -1 }, { x: 1, y: 0 }, { x: 1, y: 1 }],
      requireStructureOnFootprint: false,
      requireEmptyOffsets: [{ x: 1, y: -1 }, { x: 1, y: 0 }, { x: 1, y: 1 }],
      requireStructureBelowAnchor: true,
    },
  },
  cannonLoader: {
    mass: 8,
    hpMul: 0.85,
    type: "loader",
    loader: {
      supports: ["heavy-shot", "explosive"],
      loadMultiplier: 0.95,
      fastOperation: false,
      minLoadTime: 1.15,
      storeCapacity: 1,
      minBurstInterval: 0.5,
    },
  },
  missileLoader: {
    mass: 7,
    hpMul: 0.85,
    type: "loader",
    loader: {
      supports: ["tracking"],
      loadMultiplier: 0.92,
      fastOperation: true,
      minLoadTime: 0.85,
      storeCapacity: 1,
      minBurstInterval: 0.5,
    },
  },
  rapidGun: {
    mass: 6,
    hpMul: 0.9,
    type: "weapon",
    directional: true,
    weaponClass: "rapid-fire",
    recoil: 1.2,
    hitImpulse: 0.8,
    damage: 12,
    range: 250,
    cooldown: 0.3,
    shootAngleDeg: 118,
    projectileSpeed: 340,
    projectileGravity: PROJECTILE_GRAVITY,
    spreadDeg: 2.4,
  },
  heavyCannon: {
    mass: 12,
    hpMul: 0.9,
    type: "weapon",
    directional: true,
    weaponClass: "heavy-shot",
    recoil: 8.0,
    hitImpulse: 6.0,
    damage: 56,
    range: 330,
    cooldown: 2.8,
    shootAngleDeg: 70,
    projectileSpeed: 270,
    projectileGravity: PROJECTILE_GRAVITY,
    spreadDeg: 0.5,
  },
  explosiveShell: {
    mass: 18,
    hpMul: 0.9,
    type: "weapon",
    directional: true,
    weaponClass: "explosive",
    recoil: 14.0,
    hitImpulse: 11.0,
    damage: 42,
    range: 360,
    cooldown: 4.2,
    shootAngleDeg: 60,
    projectileSpeed: 240,
    projectileGravity: PROJECTILE_GRAVITY,
    explosive: {
      deliveryMode: "shell",
      blastRadius: 74,
      blastDamage: 36,
      falloffPower: 1.2,
      fuse: "impact",
    },
  },
  trackingMissile: {
    mass: 14,
    hpMul: 0.85,
    type: "weapon",
    directional: true,
    weaponClass: "tracking",
    recoil: 9.0,
    hitImpulse: 10.0,
    damage: 48,
    range: 470,
    cooldown: 2.2,
    shootAngleDeg: 95,
    projectileSpeed: 230,
    projectileGravity: PROJECTILE_GRAVITY,
    tracking: {
      turnRateDegPerSec: 135,
    },
  },
  precisionBeam: {
    mass: 11,
    hpMul: 0.85,
    type: "weapon",
    directional: true,
    weaponClass: "beam-precision",
    recoil: 2.0,
    hitImpulse: 2.5,
    damage: 28,
    range: 340,
    cooldown: 0.85,
    shootAngleDeg: 105,
  },
  empEmitter: {
    mass: 9,
    hpMul: 0.9,
    type: "weapon",
    directional: true,
    weaponClass: "control-utility",
    recoil: 2.6,
    hitImpulse: 1.5,
    damage: 10,
    range: 300,
    cooldown: 1.7,
    shootAngleDeg: 108,
    projectileSpeed: 260,
    projectileGravity: PROJECTILE_GRAVITY,
    control: {
      impairFactor: 0.55,
      duration: 1.8,
    },
  },
  ammo: { mass: 7, hpMul: 0.8, type: "ammo" },
};
