import type { ComponentId, ComponentStats } from "../../types.ts";
import { PROJECTILE_GRAVITY } from "./range.ts";

export const COMPONENTS: Record<ComponentId, ComponentStats> = {
  control: { mass: 8, hpMul: 0.9, gasCost: 2, type: "control" },
  engineS: {
    mass: 10,
    hpMul: 1.0,
    gasCost: 6,
    type: "engine",
    power: 92,
    maxSpeed: 96,
    propulsion: { platform: "ground", mode: "omni" },
  },
  engineM: {
    mass: 16,
    hpMul: 1.0,
    gasCost: 9,
    type: "engine",
    power: 142,
    maxSpeed: 122,
    propulsion: { platform: "ground", mode: "omni" },
  },
  jetEngine: {
    mass: 14,
    hpMul: 0.8,
    gasCost: 10,
    type: "engine",
    power: 154,
    maxSpeed: 150,
    propulsion: { platform: "air", mode: "omni" },
  },
  cannonLoader: {
    mass: 8,
    hpMul: 0.85,
    gasCost: 3,
    type: "loader",
    loader: {
      supports: ["heavy-shot", "explosive"],
      loadMultiplier: 0.95,
      fastOperation: false,
      minLoadTime: 1.15,
      minBurstInterval: 0.5,
    },
  },
  missileLoader: {
    mass: 7,
    hpMul: 0.85,
    gasCost: 3,
    type: "loader",
    loader: {
      supports: ["tracking"],
      loadMultiplier: 0.92,
      fastOperation: true,
      minLoadTime: 0.85,
      minBurstInterval: 0.5,
    },
  },
  rapidGun: {
    mass: 6,
    hpMul: 0.9,
    gasCost: 4,
    type: "weapon",
    directional: true,
    weaponClass: "rapid-fire",
    maxLoadedAmmo: 1,
    recoil: 1.2,
    hitImpulse: 0.8,
    damage: 12,
    range: 250,
    cooldown: 0.3,
    shootAngleDeg: 118,
    projectileSpeed: 340,
    projectileGravity: PROJECTILE_GRAVITY,
    penetration: 0,
    spreadDeg: 2.4,
  },
  heavyCannon: {
    mass: 12,
    hpMul: 0.9,
    gasCost: 9,
    type: "weapon",
    directional: true,
    weaponClass: "heavy-shot",
    maxLoadedAmmo: 2,
    recoil: 8.0,
    hitImpulse: 6.0,
    damage: 56,
    range: 330,
    cooldown: 2.8,
    shootAngleDeg: 70,
    projectileSpeed: 270,
    projectileGravity: PROJECTILE_GRAVITY,
    penetration: 0,
    spreadDeg: 0.5,
  },
  explosiveShell: {
    mass: 18,
    hpMul: 0.9,
    gasCost: 12,
    type: "weapon",
    directional: true,
    weaponClass: "explosive",
    maxLoadedAmmo: 2,
    recoil: 14.0,
    hitImpulse: 11.0,
    damage: 42,
    range: 360,
    cooldown: 4.2,
    shootAngleDeg: 60,
    projectileSpeed: 240,
    projectileGravity: PROJECTILE_GRAVITY,
    penetration: 0,
    explosive: {
      blastRadius: 74,
      blastDamage: 36,
      falloffPower: 1.2,
    },
  },
  trackingMissile: {
    mass: 14,
    hpMul: 0.85,
    gasCost: 11,
    type: "weapon",
    directional: true,
    weaponClass: "tracking",
    maxLoadedAmmo: 2,
    recoil: 9.0,
    hitImpulse: 10.0,
    damage: 48,
    range: 470,
    cooldown: 2.2,
    shootAngleDeg: 95,
    projectileSpeed: 230,
    projectileGravity: PROJECTILE_GRAVITY,
    penetration: 0,
    tracking: {
      turnRateDegPerSec: 135,
    },
  },
  precisionBeam: {
    mass: 11,
    hpMul: 0.85,
    gasCost: 8,
    type: "weapon",
    directional: true,
    weaponClass: "beam-precision",
    maxLoadedAmmo: 1,
    recoil: 2.0,
    hitImpulse: 2.5,
    damage: 28,
    range: 340,
    cooldown: 0.85,
    shootAngleDeg: 105,
    penetration: 0,
  },
};
