import type { ComponentId, ComponentStats } from "../../types.ts";
import { PROJECTILE_GRAVITY } from "./range.ts";

export const COMPONENTS: Record<ComponentId, ComponentStats> = {
  control: { mass: 8, hpMul: 0.9, gasCost: 2, type: "control" },
  engineS: {
    mass: 10,
    hpMul: 1.0,
    gasCost: 6,
    type: "engine",
    power: 500,
    maxSpeed: 170,
    propulsion: { platform: "ground", mode: "omni" },
  },
  engineM: {
    mass: 45,
    hpMul: 1.0,
    gasCost: 9,
    type: "engine",
    power: 900,
    maxSpeed: 65,
    propulsion: { platform: "ground", mode: "omni" },
  },
  jetEngine: {
    mass: 14,
    hpMul: 0.8,
    gasCost: 10,
    type: "engine",
    power: 600,
    maxSpeed: 320,
    propulsion: { platform: "air", mode: "omni" },
  },
  cannonLoader: {
    mass: 8,
    hpMul: 0.85,
    gasCost: 3,
    type: "loader",
    loader: {
      supports: ["heavy-shot", "explosive"],
      loadMultiplier: 0.95,
      fastOperation: false,
      minLoadTime: 1.15,
      minBurstInterval: 0.5,
    },
  },
  missileLoader: {
    mass: 7,
    hpMul: 0.85,
    gasCost: 3,
    type: "loader",
    loader: {
      supports: ["tracking"],
      loadMultiplier: 0.92,
      fastOperation: true,
      minLoadTime: 0.85,
      minBurstInterval: 0.5,
    },
  },
  rapidGun: {
    mass: 6,
    hpMul: 0.9,
    gasCost: 4,
    type: "weapon",
    directional: false,
    weaponClass: "rapid-fire",
    maxLoadedAmmo: 1,
    recoil: 1.2,
    hitImpulse: 0.8,
    damage: 5,
    range: 420,
    cooldown: 0.5,
    shootAngleDeg: 360,
    projectileSpeed: 650,
    projectileGravity: 20,
    penetration: 0,
    spreadDeg: 2.4,
  },
  heavyCannon: {
    mass: 24,
    hpMul: 0.9,
    gasCost: 9,
    type: "weapon",
    directional: true,
    weaponClass: "heavy-shot",
    maxLoadedAmmo: 2,
    recoil: 34,
    hitImpulse: 38,
    damage: 220,
    range: 680,
    cooldown: 4,
    shootAngleDeg: 70,
    projectileSpeed: 680,
    projectileGravity: 65,
    penetration: 250,
    spreadDeg: 0.25,
  },
  explosiveShell: {
    mass: 18,
    hpMul: 0.9,
    gasCost: 12,
    type: "weapon",
    directional: true,
    weaponClass: "explosive",
    maxLoadedAmmo: 2,
    recoil: 14.0,
    hitImpulse: 11.0,
    damage: 50,
    range: 360,
    cooldown: 2,
    shootAngleDeg: 60,
    projectileSpeed: 240,
    projectileGravity: PROJECTILE_GRAVITY,
    penetration: 0,
    explosive: {
      blastRadius: 100,
      blastDamage: 40,
      falloffPower: 1.2,
    },
  },
  trackingMissile: {
    mass: 14,
    hpMul: 0.85,
    gasCost: 11,
    type: "weapon",
    directional: true,
    weaponClass: "tracking",
    maxLoadedAmmo: 2,
    recoil: 9.0,
    hitImpulse: 10.0,
    damage: 48,
    range: 470,
    cooldown: 2.2,
    shootAngleDeg: 95,
    projectileSpeed: 230,
    projectileGravity: PROJECTILE_GRAVITY,
    penetration: 0,
    tracking: {
      turnRateDegPerSec: 135,
    },
  },
  precisionBeam: {
    mass: 11,
    hpMul: 0.85,
    gasCost: 8,
    type: "weapon",
    directional: true,
    weaponClass: "beam-precision",
    maxLoadedAmmo: 1,
    recoil: 2.0,
    hitImpulse: 2.5,
    damage: 5,
    range: 340,
    cooldown: 0.1,
    shootAngleDeg: 105,
    projectileSpeed: 20000,
    projectileGravity: 0,
    penetration: 0,
  },
};
